# This is a basic workflow to help you get started with Actions

name: Build App

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Create google-services.json file
      run: cat /home/runner/work/big6-android-app-store-private/big6-android-app-store-private/app/google-services.json | base64

    - name: Putting data in google-services.json
      env:
        DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $DATA > /home/runner/work/big6-android-app-store-private/big6-android-app-store-private/app/google-services.json

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Upload Artifact 
      uses: actions/upload-artifact@v3
      with:
        name: App
        path: /home/runner/work/big6-android-app-store-private/big6-android-app-store-private/app/build/outputs/apk/debug/app-debug.apk
