# This is a basic workflow to help you get started with Actions

name: BrowserStack

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Create google-services.json file
      run: cat /home/runner/work/big6-android-app-store-private/big6-android-app-store-private/app/google-services.json | base64

    - name: Putting data in google-services.json
      env:
        DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $DATA > /home/runner/work/big6-android-app-store-private/big6-android-app-store-private/app/google-services.json

    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Upload APK to BrowserStack
      env: 
        BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
        BROWSERSTACK_API_KEY: ${{ secrets.BROWSERSTACK_API_KEY }}
      run: curl -u $BROWSERSTACK_USERNAME":"$BROWSERSTACK_API_KEY -X POST "https://api-cloud.browserstack.com/app-live/upload" -F "file=@/home/runner/work/big6-android-app-store-private/big6-android-app-store-private/app/build/outputs/apk/debug/app-debug.apk"
